
package vistas;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Planeta;
import static modelos.Planeta.planetas;

/**
 *
 * @author Felipe Yan
 */
public class Frame extends javax.swing.JFrame {

    DefaultTableModel dataPlanetas = new DefaultTableModel();

    
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        
        this.txtRecNo.setText("-1");
        this.txtRecNo.setVisible(false);
        Planeta.mostrarPlanetas();
        setModelo();
        setDatos();
        tlbPlanetas.repaint();
        limpiarCampos();
    }

    public void limpiarCampos(){
        this.txtRecNo.setText("-1");
        this.txtId.setText("");
        this.txtNombre.setText("");
        this.txtUA.setText("");
        this.txtMilesk.setText("");

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelAltaInfo = new javax.swing.JPanel();
        lblAltaInformacion = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtUA = new javax.swing.JTextField();
        txtMilesk = new javax.swing.JTextField();
        txtRecNo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jPanelMostrarInfo = new javax.swing.JPanel();
        lblMostrarInfo = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbPlanetas = new javax.swing.JTable();
        tgBtnActualizar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));

        jPanelAltaInfo.setBackground(new java.awt.Color(255, 255, 204));

        lblAltaInformacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblAltaInformacion.setText("Captura Información");

        btnAñadir.setText("Añadir");
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("ID  ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Milesk");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("UA");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAltaInfoLayout = new javax.swing.GroupLayout(jPanelAltaInfo);
        jPanelAltaInfo.setLayout(jPanelAltaInfoLayout);
        jPanelAltaInfoLayout.setHorizontalGroup(
            jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAltaInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAltaInfoLayout.createSequentialGroup()
                        .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAltaInfoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblAltaInformacion)
                                .addGap(44, 44, 44))
                            .addGroup(jPanelAltaInfoLayout.createSequentialGroup()
                                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtId)
                                    .addComponent(txtUA)
                                    .addComponent(txtMilesk)
                                    .addComponent(txtNombre))))
                        .addContainerGap())
                    .addGroup(jPanelAltaInfoLayout.createSequentialGroup()
                        .addComponent(txtRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAltaInfoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(btnAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );
        jPanelAltaInfoLayout.setVerticalGroup(
            jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAltaInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAltaInformacion)
                .addGap(21, 21, 21)
                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMilesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanelAltaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnLimpiar))
                .addGap(32, 32, 32)
                .addComponent(txtRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        jPanelMostrarInfo.setBackground(new java.awt.Color(255, 204, 204));

        lblMostrarInfo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMostrarInfo.setText("Mostrar Información");

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnExportar.setText("Exportar");
        btnExportar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExportarMouseClicked(evt);
            }
        });

        tlbPlanetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tlbPlanetas);

        tgBtnActualizar.setText("Actualizar");
        tgBtnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tgBtnActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMostrarInfoLayout = new javax.swing.GroupLayout(jPanelMostrarInfo);
        jPanelMostrarInfo.setLayout(jPanelMostrarInfoLayout);
        jPanelMostrarInfoLayout.setHorizontalGroup(
            jPanelMostrarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMostrarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMostrarInfo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMostrarInfoLayout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tgBtnActualizar)
                        .addGap(37, 37, 37)
                        .addComponent(btnExportar)))
                .addGap(471, 471, 471))
            .addGroup(jPanelMostrarInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMostrarInfoLayout.setVerticalGroup(
            jPanelMostrarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMostrarInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMostrarInfo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelMostrarInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnExportar)
                    .addComponent(tgBtnActualizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFondoLayout = new javax.swing.GroupLayout(jPanelFondo);
        jPanelFondo.setLayout(jPanelFondoLayout);
        jPanelFondoLayout.setHorizontalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelAltaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelMostrarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 503, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFondoLayout.setVerticalGroup(
            jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelAltaInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMostrarInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setModelo(){
        String[] tlbCabecera = {"No ","ID","Nombre","UA","Milesk"};
        dataPlanetas.setColumnIdentifiers(tlbCabecera);
        tlbPlanetas.setModel(dataPlanetas);
    }
    
    public void setDatos(){
        Object[] datos = new Object[dataPlanetas.getColumnCount()];
        int i =0;
        dataPlanetas.setRowCount(0);
        for (Planeta planeta : planetas) {
            datos[0] = i;
            datos[1] = planeta.getiD();
            datos[2] = planeta.getNombre();
            datos[3] = planeta.getUA();
            datos[4] = planeta.getMilesk();

            i++;
            dataPlanetas.addRow(datos);
        }
        tlbPlanetas.setModel(dataPlanetas);
        
    }
    
    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
       
        int recNo = Integer.parseInt(this.txtRecNo.getText().trim());
        String iD = this.txtId.getText();
        String nombre = this.txtNombre.getText();
        String UA = this.txtUA.getText();
        String milesk = this.txtMilesk.getText();
        
              
                
        /*
        for (Planeta planeta : planetas) {
          txtAreaMostrarEvidencia.setText(txtAreaMostrarEvidencia.getText()+"\n"+planeta);
        }
       */
        
        if (recNo == -1) {
            Planeta.añadirPlanetas(UA, iD,  milesk,  nombre);
        }else{
            Planeta.actualizarPlaneta(recNo, iD, nombre, UA,milesk );
            this.tgBtnActualizar.setSelected(false);
        }

        setDatos();
        limpiarCampos(); 
        
    }//GEN-LAST:event_btnAñadirMouseClicked

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int filaActual = tlbPlanetas.getSelectedRow();

        if (filaActual != -1) {
            Planeta.eliminarPlanetas(filaActual);
            setDatos();
        } else{
            JOptionPane.showMessageDialog( null, "No hay filas existentes para eliminar");
        }
     }//GEN-LAST:event_btnEliminarMouseClicked

    private void tgBtnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tgBtnActualizarMouseClicked

        int filaActual = tlbPlanetas.getSelectedRow();
        System.out.println(filaActual);
        System.out.println(this.tgBtnActualizar.isSelected());
        
        if (this.tgBtnActualizar.isSelected()) {
            if (filaActual != -1) {
                
                this.txtRecNo.setText(""+dataPlanetas.getValueAt(filaActual, 0));
                this.txtId.setText(""+dataPlanetas.getValueAt(filaActual, 1));
                this.txtNombre.setText(""+dataPlanetas.getValueAt(filaActual, 2));
                this.txtUA.setText(""+dataPlanetas.getValueAt(filaActual, 3));
                this.txtMilesk.setText(""+dataPlanetas.getValueAt(filaActual, 4));

            }else{
                JOptionPane.showMessageDialog( null, "Debe seleccionar un registro");
                this.tgBtnActualizar.setSelected(false);
            } 
        }else{
            limpiarCampos();
        }
    }//GEN-LAST:event_tgBtnActualizarMouseClicked

    private void btnExportarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExportarMouseClicked
        System.out.println("Inico guardar archivo");
        File archivo = new File("C:\\test\\tlbPlanetas.txt");
        PrintWriter escribir;
        try {
            escribir = new PrintWriter(archivo);
            for(Planeta planeta : planetas){
                escribir.print(planeta.toString()+"\n");
            }
            escribir.close();
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExportarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelAltaInfo;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelMostrarInfo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAltaInformacion;
    private javax.swing.JLabel lblMostrarInfo;
    private javax.swing.JToggleButton tgBtnActualizar;
    private javax.swing.JTable tlbPlanetas;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMilesk;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRecNo;
    private javax.swing.JTextField txtUA;
    // End of variables declaration//GEN-END:variables
}
